### ISSUE TITLE
Bug with yaml parser.

### ISSUE THREAD

**Issue by ket4yii** [ket4yii/zait#62]
When you pass parser as yaml and pass json file it doesn't throw an error and parse it as json.

**Comment by ket4yii** [comment]
It wasn't a bug, it is feature of js-yaml and YAML schema. Changed working with configuration parsers(honestly, deleted that:smile:). @kserjey, could you close this issue.

**Comment by kserjey** [comment]
I think that it should not be in progress lable  :smiley:
